security:
    providers:
        default:
            id: dashboard.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:   ^/
            anonymous: ~
            logout: ~
            oauth:
                login_path:   /login
                use_forward:  false
                failure_path: /login
                resource_owners:
                    github: "/login/check-github"
                oauth_user_provider:
                    service: dashboard.user_provider

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/github, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
